AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 160

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'omnievent.gemspec'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassVars:
  Enabled: false
