default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: discourse_subscription_client_development

test:
  <<: *default
  database: discourse_subscription_client_test
