name: Main

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.2'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Rubocop
      run: bundle exec rubocop .

    - name: Rspec
      run: bundle exec rspec .
